Adjust git commit inspect for success/failure

diff --git a/sample-git-pr-status/pipeline-sample-git-pr-status.yaml b/sample-git-pr-status/pipeline-sample-git-pr-status.yaml
--- a/sample-git-pr-status/pipeline-sample-git-pr-status.yaml
+++ b/sample-git-pr-status/pipeline-sample-git-pr-status.yaml
@@ -127,6 +127,12 @@ spec:
               cd /artifacts/$(echo "$(params.repository)" | awk -F/ '{print $NF}' | awk -F. '{print $1}')
               git checkout $(params.branch)
               git show
+              # Exit success or failure according to fail token in log
+              if git log -1 | grep "fail"; then
+                exit 1
+              else
+                exit 0
+              fi
   finally:        
     - name: set-git-commit-status
       taskRef:
